### ISSUE TITLE
Regarding to lang

### ISSUE THREAD

**Issue by Soebb** [oliverfei/videocr-PaddleOCR#2]
Hi and thanks for this awesome repo,
Recently I got this error for 'fa' (Arabic related lang) :

AssertionError: param lang must in dict_keys(['ch', 'en', 'french', 'german', 'korean', 'japan']), but got fa

It seems the default model doesn't work for 'fa' and i need to download another model and add its path to the det_model_dir/rec_model_dir, am i right?
Does the downloaded compressed model itself contain the params?
I read the Readme but still confused.

**Comment by oliverfei** [comment]
Hello, just checking if this issue is actually resolved?

Looking at the source code, it seems 'fa' would only be supported by specifying '2.0' as the version to use for PaddleOCR, which I could add as a configurable param since the default version is '2.1' with the latest release.  https://github.com/PaddlePaddle/PaddleOCR/blob/dde7b20f03faf98cf47963a340602c77b37779c0/paddleocr.py#L194
